services:
  web:
    build: .
    env_file:
      - .env

  db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: