--
-- PostgreSQL database dump
--

\restrict 53ZH8f5bgLilHMKUc2RjVAOLnnTwBFcswyLgHhRshZBgqE9wfJEYfeqLLm53wn5

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg13+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_accounts (
    id bigint NOT NULL,
    username character varying(150) NOT NULL,
    email character varying(150) NOT NULL,
    password character varying(150) NOT NULL,
    confirm_password character varying(150) NOT NULL
);


ALTER TABLE public.accounts_accounts OWNER TO postgres;

--
-- Name: accounts_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_profile (
    id bigint NOT NULL,
    image character varying(100),
    phone character varying(20) NOT NULL,
    gender character varying(20) NOT NULL,
    date_of_birth date,
    country character varying(100) NOT NULL,
    city character varying(100) NOT NULL,
    bio text NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.accounts_profile OWNER TO postgres;

--
-- Name: accounts_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_cart; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cart_cart (
    id bigint NOT NULL,
    quantity bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT cart_cart_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.cart_cart OWNER TO postgres;

--
-- Name: cart_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cart_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.categories_category OWNER TO postgres;

--
-- Name: categories_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: orders_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_order (
    id bigint NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    razorpay_order_id character varying(255),
    razorpay_payment_id character varying(255),
    razorpay_signature character varying(500),
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.orders_order OWNER TO postgres;

--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_orderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT orders_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.orders_orderitem OWNER TO postgres;

--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_products (
    id bigint NOT NULL,
    name character varying(260) NOT NULL,
    brand character varying(150) NOT NULL,
    price numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    image character varying(100) NOT NULL,
    description text NOT NULL,
    category_id bigint NOT NULL,
    rating numeric(2,1) NOT NULL,
    hero_position character varying(20),
    CONSTRAINT products_products_stock_check CHECK ((stock >= 0))
);


ALTER TABLE public.products_products OWNER TO postgres;

--
-- Name: products_products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_specification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_specification (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    value text NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.products_specification OWNER TO postgres;

--
-- Name: products_specification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_specification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_specification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_trendingproduct; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_trendingproduct (
    id bigint NOT NULL,
    category character varying(50) NOT NULL,
    "order" integer NOT NULL,
    is_active boolean NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT products_trendingproduct_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.products_trendingproduct OWNER TO postgres;

--
-- Name: products_trendingproduct_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_trendingproduct ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_trendingproduct_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews_reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews_reviews (
    id bigint NOT NULL,
    rating integer NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT reviews_review_rating_check CHECK ((rating >= 0))
);


ALTER TABLE public.reviews_reviews OWNER TO postgres;

--
-- Name: reviews_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews_reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlist_wishlist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wishlist_wishlist (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    products_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.wishlist_wishlist OWNER TO postgres;

--
-- Name: wishlist_wishlist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wishlist_wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_accounts (id, username, email, password, confirm_password) FROM stdin;
\.


--
-- Data for Name: accounts_profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_profile (id, image, phone, gender, date_of_birth, country, city, bio, user_id) FROM stdin;
2				\N				1
3				\N				4
4				\N				2
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add accounts	7	add_accounts
26	Can change accounts	7	change_accounts
27	Can delete accounts	7	delete_accounts
28	Can view accounts	7	view_accounts
29	Can add profile	8	add_profile
30	Can change profile	8	change_profile
31	Can delete profile	8	delete_profile
32	Can view profile	8	view_profile
33	Can add products	9	add_products
34	Can change products	9	change_products
35	Can delete products	9	delete_products
36	Can view products	9	view_products
37	Can add specification	10	add_specification
38	Can change specification	10	change_specification
39	Can delete specification	10	delete_specification
40	Can view specification	10	view_specification
41	Can add trending product	11	add_trendingproduct
42	Can change trending product	11	change_trendingproduct
43	Can delete trending product	11	delete_trendingproduct
44	Can view trending product	11	view_trendingproduct
45	Can add cart	12	add_cart
46	Can change cart	12	change_cart
47	Can delete cart	12	delete_cart
48	Can view cart	12	view_cart
49	Can add order	13	add_order
50	Can change order	13	change_order
51	Can delete order	13	delete_order
52	Can view order	13	view_order
53	Can add order item	14	add_orderitem
54	Can change order item	14	change_orderitem
55	Can delete order item	14	delete_orderitem
56	Can view order item	14	view_orderitem
57	Can add reviews	15	add_reviews
58	Can change reviews	15	change_reviews
59	Can delete reviews	15	delete_reviews
60	Can view reviews	15	view_reviews
61	Can add category	16	add_category
62	Can change category	16	change_category
63	Can delete category	16	delete_category
64	Can view category	16	view_category
65	Can add wishlist	17	add_wishlist
66	Can change wishlist	17	change_wishlist
67	Can delete wishlist	17	delete_wishlist
68	Can view wishlist	17	view_wishlist
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$ogBze9cIUlm3xLxvRlYPov$TkdFSeCHEinYvXfFNbeOiNxzgc9mNpkjNBQWDWZKm2A=	2026-09-02 03:58:41.523+00	f	rahulrameshm0			rahulrameshm23@gmail.com	f	t	2026-06-30 15:28:26.791+00
2	pbkdf2_sha256$1200000$XjUrAKSTn5oCQG5ERUkGw3$o77NEmKqBLmoqdsTrTGI3nBXCvBPtlIeeFa15NVe/0o=	2026-09-02 04:05:51.685+00	t	rahul				t	t	2026-07-15 22:06:16.325+00
4	pbkdf2_sha256$1200000$mmx1Sdj0e36UPBCCmX7Ems$tYxSqVS6vQ3t3CzhgZKq1jMZvT4R8f7xOsZtmnBu05Q=	2026-08-15 08:10:21.123+00	f	james@23			jameshunt@gmail.com	f	t	2026-08-15 08:09:54.629+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: cart_cart; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cart_cart (id, quantity, created_at, product_id, user_id) FROM stdin;
22	1	2026-08-15 06:31:19.596+00	11	1
49	2	2026-08-24 07:54:23.701+00	11	2
\.


--
-- Data for Name: categories_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories_category (id, name) FROM stdin;
1	Smartphones
3	Laptops
4	Smart Watches
5	Cameras
6	Headphones
7	Gaming
8	Accessories
9	Wired Cable
10	Luggage
11	Electronics
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	accounts	accounts
8	accounts	profile
9	products	products
10	products	specification
11	products	trendingproduct
12	cart	cart
13	orders	order
14	orders	orderitem
15	reviews	reviews
16	categories	category
17	wishlist	wishlist
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-02 16:45:40.337241+00
2	auth	0001_initial	2026-09-02 16:45:40.361971+00
3	accounts	0001_initial	2026-09-02 16:45:40.365756+00
4	accounts	0002_remove_accounts_phone	2026-09-02 16:45:40.367759+00
5	accounts	0003_profile	2026-09-02 16:45:40.377181+00
6	admin	0001_initial	2026-09-02 16:45:40.384717+00
7	admin	0002_logentry_remove_auto_add	2026-09-02 16:45:40.390506+00
8	admin	0003_logentry_add_action_flag_choices	2026-09-02 16:45:40.395217+00
9	contenttypes	0002_remove_content_type_name	2026-09-02 16:45:40.404998+00
10	auth	0002_alter_permission_name_max_length	2026-09-02 16:45:40.411544+00
11	auth	0003_alter_user_email_max_length	2026-09-02 16:45:40.417478+00
12	auth	0004_alter_user_username_opts	2026-09-02 16:45:40.4247+00
13	auth	0005_alter_user_last_login_null	2026-09-02 16:45:40.430765+00
14	auth	0006_require_contenttypes_0002	2026-09-02 16:45:40.431356+00
15	auth	0007_alter_validators_add_error_messages	2026-09-02 16:45:40.4364+00
16	auth	0008_alter_user_username_max_length	2026-09-02 16:45:40.441089+00
17	auth	0009_alter_user_last_name_max_length	2026-09-02 16:45:40.44514+00
18	auth	0010_alter_group_name_max_length	2026-09-02 16:45:40.450949+00
19	auth	0011_update_proxy_permissions	2026-09-02 16:45:40.455962+00
20	auth	0012_alter_user_first_name_max_length	2026-09-02 16:45:40.461285+00
21	categories	0001_initial	2026-09-02 16:45:40.465249+00
22	products	0001_initial	2026-09-02 16:45:40.471881+00
23	products	0002_specification	2026-09-02 16:45:40.476396+00
24	products	0003_products_rating	2026-09-02 16:45:40.482605+00
25	cart	0001_initial	2026-09-02 16:45:40.491697+00
26	products	0004_products_hero_position	2026-09-02 16:45:40.494073+00
27	products	0005_alter_products_hero_position	2026-09-02 16:45:40.496038+00
28	products	0006_alter_products_hero_position	2026-09-02 16:45:40.500703+00
29	products	0007_alter_products_hero_position	2026-09-02 16:45:40.505378+00
30	products	0008_alter_products_hero_position	2026-09-02 16:45:40.508888+00
31	orders	0001_initial	2026-09-02 16:45:40.530999+00
32	products	0009_trendingproduct	2026-09-02 16:45:40.544715+00
33	reviews	0001_initial	2026-09-02 16:45:40.557001+00
34	reviews	0002_rename_review_reviews	2026-09-02 16:45:40.578949+00
35	reviews	0003_rename_comments_reviews_comment	2026-09-02 16:45:40.58772+00
36	sessions	0001_initial	2026-09-02 16:45:40.593105+00
37	wishlist	0001_initial	2026-09-02 16:45:40.667901+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: orders_order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_order (id, total_amount, status, razorpay_order_id, razorpay_payment_id, razorpay_signature, created_at, user_id) FROM stdin;
1	500.00	PENDING	order_TTXroMBqAYGq7f	\N	\N	2026-08-24 08:44:02.456+00	2
2	500.00	PENDING	order_TTXtIY8yJbCoCB	\N	\N	2026-08-24 08:45:26.902+00	2
3	500.00	PENDING	order_TTYPw7kRWJyvOf	\N	\N	2026-08-24 09:16:20.485+00	2
4	500.00	PENDING	order_TTYPyP9lCfWVO3	\N	\N	2026-08-24 09:16:22.905+00	2
5	500.00	PENDING	order_TTYTDm0pZH2aMX	\N	\N	2026-08-24 09:19:27.208+00	2
6	500.00	PENDING	order_TTYTRyPgfbYJue	\N	\N	2026-08-24 09:19:39.275+00	2
7	500.00	PENDING	order_TTYVQJdUBOm2gB	\N	\N	2026-08-24 09:21:32.387+00	2
8	500.00	PENDING	order_TTYVTAVsQh3cbV	\N	\N	2026-08-24 09:21:35.101+00	2
9	500.00	PENDING	order_TTYWNYkzjmwecO	\N	\N	2026-08-24 09:22:26.633+00	2
10	500.00	PENDING	order_TTYXIukbMXPm1u	\N	\N	2026-08-24 09:23:19.204+00	2
11	500.00	PENDING	order_TTYdbiB4HDYcvr	\N	\N	2026-08-24 09:29:17.219+00	2
12	500.00	PENDING	order_TTYf6AWy0RPgFN	\N	\N	2026-08-24 09:30:41.664+00	2
13	500.00	PENDING	order_TTYfwA3QKVRFJx	\N	\N	2026-08-24 09:31:29.529+00	2
14	500.00	PENDING	order_TTYiJxKs44g9rN	\N	\N	2026-08-24 09:33:44.887+00	2
15	500.00	PENDING	order_TTYiRFmZ2DCz5G	\N	\N	2026-08-24 09:33:51.768+00	2
16	500.00	PENDING	order_TTYigDJ4k2KsNv	\N	\N	2026-08-24 09:34:05.413+00	2
17	500.00	PENDING	order_TTYjCm4mFpGG6E	\N	\N	2026-08-24 09:34:35.22+00	2
18	500.00	PENDING	order_TTYjPkO1EIZr1j	\N	\N	2026-08-24 09:34:47.185+00	2
19	500.00	PENDING	order_TTYjeF3lc1yPUf	\N	\N	2026-08-24 09:35:00.395+00	2
20	500.00	PENDING	order_TTYjkNraGUu2gE	\N	\N	2026-08-24 09:35:05.79+00	2
21	500.00	PENDING	order_TTYnb4yXi2QVan	\N	\N	2026-08-24 09:38:44.464+00	2
22	500.00	PENDING	order_TTYoaHJ40bJLIT	\N	\N	2026-08-24 09:39:40.756+00	2
23	500.00	PENDING	order_TTYp5tudiaajff	\N	\N	2026-08-24 09:40:09.476+00	2
24	500.00	PENDING	order_TTYraD074B7p90	\N	\N	2026-08-24 09:42:31.017+00	2
25	500.00	PENDING	order_TTYsMomY5HPYSC	\N	\N	2026-08-24 09:43:15.647+00	2
26	500.00	PENDING	order_TTYucHvSvKX4ml	\N	\N	2026-08-24 09:45:23.262+00	2
27	500.00	PENDING	order_TTZHoQZQDAoQEs	\N	\N	2026-08-24 10:07:20.776+00	2
28	500.00	PENDING	order_TTZI1fr5I4AocU	\N	\N	2026-08-24 10:07:33.044+00	2
29	500.00	PENDING	order_TTZKoh2mxzEKZ4	\N	\N	2026-08-24 10:10:11.366+00	2
30	500.00	PENDING	order_TTdRbZZcBO0hYJ	\N	\N	2026-08-24 14:11:23.342+00	2
31	500.00	PENDING	order_TTdWoxiTexHwBl	\N	\N	2026-08-24 14:16:19.823+00	2
32	2000.00	PENDING	order_TTdXlvLD5TyemB	\N	\N	2026-08-24 14:17:13.94+00	1
33	2000.00	PENDING	order_TTde9LiZEfD6AQ	\N	\N	2026-08-24 14:23:16.214+00	1
34	2000.00	PENDING	order_TTdeFz8MtctvjI	\N	\N	2026-08-24 14:23:22.311+00	1
35	2000.00	PENDING	order_TTdfPv3myN6w1Z	\N	\N	2026-08-24 14:24:28.171+00	1
36	2000.00	PENDING	order_TTdh0i1e8rPFGc	\N	\N	2026-08-24 14:25:58.711+00	1
37	2000.00	PENDING	order_TTdhCCs4T4irue	\N	\N	2026-08-24 14:26:09.235+00	1
38	2000.00	PENDING	order_TTdr73nFvEuRqj	\N	\N	2026-08-24 14:35:32.469+00	1
39	2000.00	PENDING	order_TTdtp7xhVcrJw6	\N	\N	2026-08-24 14:38:06.452+00	1
40	2000.00	PENDING	order_TTdtv7cgRDwpuz	\N	\N	2026-08-24 14:38:11.965+00	1
41	2000.00	PENDING	order_TTe1Ym6AHluWnQ	\N	\N	2026-08-24 14:45:25.822+00	1
42	2000.00	PENDING	order_TTe56wK75bLp5u	\N	\N	2026-08-24 14:48:47.547+00	1
43	2000.00	PENDING	order_TTe5PvC8mFVCu4	\N	\N	2026-08-24 14:49:04.866+00	1
44	2000.00	PENDING	order_TTe64bG3p5VE4O	\N	\N	2026-08-24 14:49:42.222+00	1
45	2000.00	PENDING	order_TTeKiahrKF7ydO	\N	\N	2026-08-24 15:03:34.056+00	1
46	2000.00	PENDING	order_TTeLC96uAmMPON	\N	\N	2026-08-24 15:04:01.227+00	1
47	2000.00	PENDING	order_TTekJVvwyQUoja	\N	\N	2026-08-24 15:27:47.922+00	1
48	2000.00	PENDING	order_TTeoYwBzQK0VhP	\N	\N	2026-08-24 15:31:49.298+00	1
49	1999.00	PENDING	order_TTeyNE6LDDq6Bh	\N	\N	2026-08-24 15:41:06.485+00	1
50	1999.00	PENDING	order_TTeyfnzerj7T19	\N	\N	2026-08-24 15:41:23.562+00	1
51	1999.00	PENDING	order_TTeyixpCPZ07Rt	\N	\N	2026-08-24 15:41:26.472+00	1
52	1999.00	PENDING	order_TTeynC54Z7L0s8	\N	\N	2026-08-24 15:41:30.346+00	1
53	1999.00	PENDING	order_TTez3cHRwfjMxI	\N	\N	2026-08-24 15:41:45.389+00	1
54	1999.00	PENDING	order_TTf1b0WT635Qgv	\N	\N	2026-08-24 15:44:09.476+00	1
55	1999.00	PENDING	order_TTgFHZh30UkDud	\N	\N	2026-08-24 16:55:48.491+00	1
56	1999.00	PENDING	order_TTgLRPus0qjFY2	\N	\N	2026-08-24 17:01:38.407+00	1
\.


--
-- Data for Name: orders_orderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_orderitem (id, quantity, price, order_id, product_id) FROM stdin;
1	1	500.00	1	11
2	1	500.00	2	11
3	1	500.00	3	11
4	1	500.00	4	11
5	1	500.00	5	11
6	1	500.00	6	11
7	1	500.00	7	11
8	1	500.00	8	11
9	1	500.00	9	11
10	1	500.00	10	11
11	1	500.00	11	11
12	1	500.00	12	11
13	1	500.00	13	11
14	1	500.00	14	11
15	1	500.00	15	11
16	1	500.00	16	11
17	1	500.00	17	11
18	1	500.00	18	11
19	1	500.00	19	11
20	1	500.00	20	11
21	1	500.00	21	11
22	1	500.00	22	11
23	1	500.00	23	11
24	1	500.00	24	11
25	1	500.00	25	11
26	1	500.00	26	11
27	1	500.00	27	11
28	1	500.00	28	11
29	1	500.00	29	11
30	1	500.00	30	11
31	1	500.00	31	11
32	1	2000.00	32	5
33	1	2000.00	33	5
34	1	2000.00	34	5
35	1	2000.00	35	5
36	1	2000.00	36	5
37	1	2000.00	37	5
38	1	2000.00	38	5
39	1	2000.00	39	5
40	1	2000.00	40	5
41	1	2000.00	41	5
42	1	2000.00	42	5
43	1	2000.00	43	5
44	1	2000.00	44	5
45	1	2000.00	45	5
46	1	2000.00	46	5
47	1	2000.00	47	5
48	1	2000.00	48	5
49	1	1999.00	49	12
50	1	1999.00	50	12
51	1	1999.00	51	12
52	1	1999.00	52	12
53	1	1999.00	53	12
54	1	1999.00	54	12
55	1	1999.00	55	12
56	1	1999.00	56	12
\.


--
-- Data for Name: products_products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_products (id, name, brand, price, stock, image, description, category_id, rating, hero_position) FROM stdin;
4	Samsung Galaxy S24 Ultra	Samsung	2000.00	3	products/S24_Ultra_7s9omCK.jpg	Samsung Galaxy S24 Ultra	1	3.8	phone
5	Apple Watch	Apple	2000.00	4	products/daniel-korpai-hbTKIbuMmBI-unsplash.jpg	Apple Watch	4	3.6	watch
6	Canon Camera	Canon	3999.00	6	products/andrew-hutchings-W2Dta_Yiwfw-unsplash.jpg	Canon Camera	5	3.5	camera
7	Sony Wireless Headphone	Sony	2999.00	25	products/luke-peterson-lUMj2Zv5HUE-unsplash.jpg	Sony Wireless	6	4.3	\N
8	SONY, ILCE-6000	Sony	1999.00	56	products/frank-septillion-Qrspubmx6kE-unsplash.jpg	SONY, ILCE-6000	6	4.0	dslr
9	Apple Headphones	Apple	3599.00	56	products/ravi-palwe-ax23KYiUdJc-unsplash.jpg	Apple Headphones	6	3.4	earbuds
10	Ant Esports Optical Gaming Keyboard	Kreo Swarm	3999.00	8	products/gaming-keyboard.jpg	Ant Esports GM100 V2 Optical Gaming Mouse,7 Button Wired USB Mouse, 4000 FPS Sensor, 3600 DPI, RGB Lighting,1.5m PVC Cable, Ergonomic Design, for Windows PC, Laptop,Gaming & Office Use- Black & White	7	3.0	\N
11	Apple HomePod	Apple HomePod  (2nd Generation) - Midnight	500.00	50	products/apple-homepod-webp.webp	HomePod is a powerhouse of a speaker. Apple‑engineered\r\naudio technology and advanced software deliver high‑fidelity\r\nsound throughout the room. It intelligently adapts to whatever it’s\r\nplaying — or wherever it’s playing — and surrounds you in immersive audio that makes everything you listen to sound incredible	6	4.0	homepod
12	Lenovo ThinkPad P16s Gen 4	Lenovo	1999.00	55	products/lenovo.avif	Run your CAD, BIM, and creative apps with confidence, backed by independent software vendor (ISV)* certifications from ANSYS®, SOLIDWORKS®, AutoCAD®, and more. Delivering pro-level performance, the ThinkPad P16s Gen 4 mobile workstation amplifies work efficiency for smarter, more intuitive workflows.	3	4.7	\N
13	XIAOMI 17 Ultra (Black, 16GB+512GB)	XIAOMI	1499.00	150	products/xiaomi.jpg	XIAOMI 17 Ultra (Black, 16GB+512GB) |World's First Leica 1-Inch LOFIC Sensor |Snapdragon 8 Elite Gen 5 |2K AMOLED Display | 90W HyperCharge HyperOS 3 | HyperAI Flagship Experience	1	4.0	phone
14	Wired Cable	Silicone Cable Protector	2.00	250	products/silcon_cable.webp	4 in 1 Silicone Cable Protector – Durable Wire Saver for Charger & Earphone Cable (Random color- Pack of 1)	9	3.5	\N
15	Luggage Trolley	Transparent Luggage	1.50	206	products/LuggageTrolley.webp	Transparent Luggage Trolley Waterproof Cover – Dustproof & Scratch-Resistant Suitcase Protector	10	3.0	\N
16	Silicone Back Scrubber	Silicone Back Scrubber	1.00	25	products/Untitled_design_32_7869ad7a-5c91-4508-b6dc-5738a664b7b3.webp	Silicone Back Scrubber – Dual-Sided Exfoliating & Massage Body Brush | Quick-Drying, Hygienic Bath Scrubber for Deep Cleaning (Random Color – Pack of 1)	8	3.2	\N
17	Rainbow Metallic Cable Protector	Cable Protector	15.00	25	products/100ml_2.webp	Rainbow Metallic Cable Protector – 150 cm Spiral Wire Organizer for Charging Cables (Multicolor-Pack of 1)	11	5.0	\N
\.


--
-- Data for Name: products_specification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_specification (id, name, value, product_id) FROM stdin;
1	Brand	Samsung	4
2	Model	Galaxy S24 Ultra	4
3	Operating System	Android 14 (Upgradeable to newer versions), One UI	4
4	Processor	Qualcomm Snapdragon 8 Gen 3 for Galaxy	4
5	CPU	Octa-core	4
6	GPU	Adreno 750	4
7	RAM	12 GB	4
8	Storage	256 GB / 512 GB / 1 TB	4
9	Resolution	3120 × 1440 pixels (QHD+)	4
10	Refresh Rate	1–120 Hz Adaptive	4
11	Peak Brightness	2600 nits	4
12	Screen Protection	Corning Gorilla Glass Armor	4
13	Rear Camera	200 MP (Wide) + 50 MP (Periscope Telephoto, 5× Optical Zoom) + 10 MP (Telephoto, 3× Optical Zoom) + 12 MP (Ultra-wide)	4
14	Battery	5000 mAh	4
15	SIM	Dual SIM (Nano-SIM + eSIM)	4
16	Frame	Material Titanium	4
17	Brand	Apple	5
18	Model	Apple Watch Series 10	5
19	Chip	Apple S10 SiP	5
20	Display	Always-On Retina OLED	5
21	Storage	64 GB	5
22	Connectivity	GPS, Wi-Fi, Bluetooth 5.3	5
23	Battery Life	Up to 18 hours	5
24	Water	Resistance 50 m	5
25	Health Features	Heart Rate, ECG, Blood Oxygen, Sleep Tracking	5
26	Sensors	Heart Rate, Accelerometer, Gyroscope	5
27	Operating System	watchOS 11	5
28	Material	Aluminum	5
29	Colors	Jet Black, Rose Gold, Silver	5
30	Warranty	1 Year	5
31	Brand	Canon	6
32	Model	EOS Rebel T5i (EOS 700D)	6
34	Camera Type	18 MP APS-C CMOS	6
35	Sensor	18 MP APS-C CMOS	6
36	Image Processor	DIGIC 5	6
37	ISO Range	100–12800 (Expandable to 25600)	6
38	Autofocus	9-Point AF System	6
39	Continuous	Shooting Up to 5 fps	6
40	Video	Recording Full HD 1080p	6
41	Display	3.0-inch Vari-Angle Touchscreen LCD	6
42	Lens Mount	Canon EF / EF-S	6
43	Viewfinder	Optical	6
44	Connectivity	USB, HDMI	6
45	Storage	SD / SDHC / SDXC Memory Card	6
46	Battery	LP-E8 Rechargeable Battery	6
47	Weight	Approx. 580 g	6
48	Color	Black	6
49	Brand	Sony	6
50	Connectivity	Bluetooth 5.2	7
51	Battery Life	Up to 30 hours	7
52	Noise Cancellation	Active Noise Cancellation (ANC)	7
53	Driver Size	40 mm	7
54	Charging Port	USB Type-C	7
55	Built-in Microphone	Yes	7
56	Warranty	1 Year	7
57	Brand	Sony	8
58	Model	ILCE-6000	6
59	Sensor	24.3 MP APS-C CMOS	8
60	Video Recording	Full HD 1080p	8
61	Display	3-inch Tilting LCD	8
62	Connectivity	Wi-Fi & NFC	8
63	Connectivity	Wi-Fi & NFC	8
64	Autofocus	179-Point Fast Hybrid AF	8
65	Battery Life	Up to 360 Shots	8
66	Brand	Apple	9
67	Connectivity	Bluetooth 5.0	9
68	Noise Cancellation	Active Noise Cancellation	9
69	Spatial Audio	Supported	9
70	Battery Life	Up to 20 Hours	9
71	Charging Port	Lightning / USB-C (depending on model)	9
72	Built-in Microphone	Yes	9
73	Compatibility	iPhone, iPad, Mac	9
74	Brand	Ant Esports	10
75	DPI	Up to 3600 DPI	10
76	Buttons	7 Programmable Buttons	10
77	Connectivity	Wired USB	10
78	RGB Lighting	Yes	9
79	Cable Length	1.5 m PVC Cable	10
80	Compatibility	Windows, macOS, Linux	10
81	Weight	Lightweight Ergonomic Design	10
82	Brand	Apple	11
83	Model	HomePod (2nd Generation)	11
84	Speaker Type	Smart Speaker	11
85	Connectivity	Wi-Fi & Bluetooth 5.0	11
86	Voice Assistant	Siri	11
87	Audio Features	Spatial Audio with Dolby Atmos	11
88	Smart Home Support	Apple HomeKit & Matter	11
89	Power Source	AC Power Adapter	11
90	Processor	Intel® Core™ Ultra 7 255H Processor (E-cores up to 4.40 GHz P-cores up to 5.10 GHz)	12
91	Graphic Card	Integrated Graphics	12
92	Memory	16 GB DDR5-5600MT/s (SODIMM)	12
93	Storage	512 GB SSD M.2 2280 PCIe Gen4 TLC Opal	12
94	Display	40.64cms (16) WUXGA (1920 x 1200), IPS, Anti-Glare, Non-Touch, 45%NTSC, 400 nits, 60Hz	12
95	AC Adapter / Power Supply	100W USB-C Slim 90% PCC 3pin AC Adapter - India	12
96	Keyboard	Backlit, Black with Number Pad - English (US)	12
97	WIFI	Intel® Wi-Fi 7 BE201 2x2 BE & Bluetooth® 5.4	12
98	Warranty	3 Year On-site	12
99	Color	Color	12
100	Color	Black	12
101	Brand	ThinkPad P16s Gen 4	12
\.


--
-- Data for Name: products_trendingproduct; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_trendingproduct (id, category, "order", is_active, product_id) FROM stdin;
1	Mobile	5	t	13
2	Accessories	0	t	14
3	Luggage	0	t	15
4	Acessories	2	t	16
5	Accessories	0	t	17
6	Speaker	0	t	11
\.


--
-- Data for Name: reviews_reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reviews_reviews (id, rating, comment, created_at, product_id, user_id) FROM stdin;
1	2	The Product is so good, I like the UI , this is far better than Iphone, just try one.	2026-07-24 10:44:03.487+00	4	1
2	3	The product is fine	2026-07-24 18:31:25.337+00	4	2
3	5	I like the watch, this is fine	2026-07-24 18:35:39.164+00	5	2
4	4	I like the sensor of that camera, nice photos	2026-07-24 18:37:03.39+00	6	1
5	3	Not good Enough	2026-07-24 18:37:26.644+00	7	2
6	3	So, smooth an clear	2026-07-24 18:37:48.564+00	8	1
7	3	It's okay okay	2026-07-24 18:38:43.116+00	9	1
8	3	I like the Keyboard, especially the smoothness of typing, it so great, though the amount is bit high, I think you can buy better products than this, but still it's good enough.	2026-07-24 18:40:25.998+00	10	1
\.


--
-- Data for Name: wishlist_wishlist; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wishlist_wishlist (id, created_at, products_id, user_id) FROM stdin;
13	2026-08-15 06:31:26.319+00	11	1
14	2026-08-19 09:17:15.121+00	4	2
\.


--
-- Name: accounts_accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_accounts_id_seq', 1, false);


--
-- Name: accounts_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_profile_id_seq', 4, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 4, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: cart_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cart_cart_id_seq', 49, true);


--
-- Name: categories_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_category_id_seq', 11, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 37, true);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 56, true);


--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_orderitem_id_seq', 56, true);


--
-- Name: products_products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_products_id_seq', 17, true);


--
-- Name: products_specification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_specification_id_seq', 101, true);


--
-- Name: products_trendingproduct_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_trendingproduct_id_seq', 6, true);


--
-- Name: reviews_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reviews_review_id_seq', 8, true);


--
-- Name: wishlist_wishlist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.wishlist_wishlist_id_seq', 14, true);


--
-- Name: accounts_accounts accounts_accounts_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_accounts
    ADD CONSTRAINT accounts_accounts_email_key UNIQUE (email);


--
-- Name: accounts_accounts accounts_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_accounts
    ADD CONSTRAINT accounts_accounts_pkey PRIMARY KEY (id);


--
-- Name: accounts_accounts accounts_accounts_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_accounts
    ADD CONSTRAINT accounts_accounts_username_key UNIQUE (username);


--
-- Name: accounts_profile accounts_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_pkey PRIMARY KEY (id);


--
-- Name: accounts_profile accounts_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: cart_cart cart_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_pkey PRIMARY KEY (id);


--
-- Name: cart_cart cart_cart_user_id_product_id_c290cfe1_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_user_id_product_id_c290cfe1_uniq UNIQUE (user_id, product_id);


--
-- Name: categories_category categories_category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories_category
    ADD CONSTRAINT categories_category_name_key UNIQUE (name);


--
-- Name: categories_category categories_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories_category
    ADD CONSTRAINT categories_category_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: orders_order orders_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_pkey PRIMARY KEY (id);


--
-- Name: orders_orderitem orders_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_pkey PRIMARY KEY (id);


--
-- Name: products_products products_products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_products
    ADD CONSTRAINT products_products_pkey PRIMARY KEY (id);


--
-- Name: products_specification products_specification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_specification
    ADD CONSTRAINT products_specification_pkey PRIMARY KEY (id);


--
-- Name: products_trendingproduct products_trendingproduct_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_trendingproduct
    ADD CONSTRAINT products_trendingproduct_pkey PRIMARY KEY (id);


--
-- Name: reviews_reviews reviews_review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_reviews
    ADD CONSTRAINT reviews_review_pkey PRIMARY KEY (id);


--
-- Name: wishlist_wishlist wishlist_wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_pkey PRIMARY KEY (id);


--
-- Name: wishlist_wishlist wishlist_wishlist_user_id_products_id_a6cc7345_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_user_id_products_id_a6cc7345_uniq UNIQUE (user_id, products_id);


--
-- Name: accounts_accounts_email_da8a4382_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_accounts_email_da8a4382_like ON public.accounts_accounts USING btree (email varchar_pattern_ops);


--
-- Name: accounts_accounts_username_a6d49ba5_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_accounts_username_a6d49ba5_like ON public.accounts_accounts USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: cart_cart_product_id_b5f94649; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cart_cart_product_id_b5f94649 ON public.cart_cart USING btree (product_id);


--
-- Name: cart_cart_user_id_9b4220b9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cart_cart_user_id_9b4220b9 ON public.cart_cart USING btree (user_id);


--
-- Name: categories_category_name_debcfc14_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX categories_category_name_debcfc14_like ON public.categories_category USING btree (name varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: orders_order_user_id_e9b59eb1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_order_user_id_e9b59eb1 ON public.orders_order USING btree (user_id);


--
-- Name: orders_orderitem_order_id_fe61a34d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_orderitem_order_id_fe61a34d ON public.orders_orderitem USING btree (order_id);


--
-- Name: orders_orderitem_product_id_afe4254a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_orderitem_product_id_afe4254a ON public.orders_orderitem USING btree (product_id);


--
-- Name: products_products_category_id_0cfaa6ce; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_products_category_id_0cfaa6ce ON public.products_products USING btree (category_id);


--
-- Name: products_specification_product_id_9301529f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_specification_product_id_9301529f ON public.products_specification USING btree (product_id);


--
-- Name: products_trendingproduct_product_id_20f6bb0d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_trendingproduct_product_id_20f6bb0d ON public.products_trendingproduct USING btree (product_id);


--
-- Name: reviews_review_product_id_ce2fa4c6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_review_product_id_ce2fa4c6 ON public.reviews_reviews USING btree (product_id);


--
-- Name: reviews_review_user_id_875caff2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_review_user_id_875caff2 ON public.reviews_reviews USING btree (user_id);


--
-- Name: wishlist_wishlist_products_id_3bc90199; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wishlist_wishlist_products_id_3bc90199 ON public.wishlist_wishlist USING btree (products_id);


--
-- Name: wishlist_wishlist_user_id_13f28b16; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wishlist_wishlist_user_id_13f28b16 ON public.wishlist_wishlist USING btree (user_id);


--
-- Name: accounts_profile accounts_profile_user_id_49a85d32_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_49a85d32_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cart cart_cart_product_id_b5f94649_fk_products_products_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_product_id_b5f94649_fk_products_products_id FOREIGN KEY (product_id) REFERENCES public.products_products(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cart cart_cart_user_id_9b4220b9_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_user_id_9b4220b9_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_user_id_e9b59eb1_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_user_id_e9b59eb1_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_order_id_fe61a34d_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_order_id_fe61a34d_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_product_id_afe4254a_fk_products_products_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_product_id_afe4254a_fk_products_products_id FOREIGN KEY (product_id) REFERENCES public.products_products(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_products products_products_category_id_0cfaa6ce_fk_categorie; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_products
    ADD CONSTRAINT products_products_category_id_0cfaa6ce_fk_categorie FOREIGN KEY (category_id) REFERENCES public.categories_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_specification products_specificati_product_id_9301529f_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_specification
    ADD CONSTRAINT products_specificati_product_id_9301529f_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_products(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_trendingproduct products_trendingpro_product_id_20f6bb0d_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_trendingproduct
    ADD CONSTRAINT products_trendingpro_product_id_20f6bb0d_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_products(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reviews_reviews reviews_review_product_id_ce2fa4c6_fk_products_products_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_reviews
    ADD CONSTRAINT reviews_review_product_id_ce2fa4c6_fk_products_products_id FOREIGN KEY (product_id) REFERENCES public.products_products(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reviews_reviews reviews_review_user_id_875caff2_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_reviews
    ADD CONSTRAINT reviews_review_user_id_875caff2_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wishlist_wishlist wishlist_wishlist_products_id_3bc90199_fk_products_products_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_products_id_3bc90199_fk_products_products_id FOREIGN KEY (products_id) REFERENCES public.products_products(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wishlist_wishlist wishlist_wishlist_user_id_13f28b16_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_user_id_13f28b16_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 53ZH8f5bgLilHMKUc2RjVAOLnnTwBFcswyLgHhRshZBgqE9wfJEYfeqLLm53wn5

