# Generated by Django 6.0.6 on 2026-07-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_review_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='comments',
            new_name='comment',
        ),
    ]
