# Generated by Django 6.0.6 on 2026-07-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hero_position',
            field=models.CharField(blank=True, choices=[('homepod', 'HomePod'), ('watch', 'Watch'), ('phone', 'Phone'), ('camera', 'Camera'), ('earbuds', 'Earbuds'), ('dslr', 'DSLR')], max_length=20, null=True),
        ),
    ]
