# Generated by Django 6.0.6 on 2026-08-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_hero_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='hero_position',
            field=models.CharField(blank=True, choices=[('homepod', 'HomePod'), ('watch', 'Watch'), ('phone', 'Phone'), ('camera', 'Camera'), ('earbuds', 'Earbuds'), ('dslr', 'DSLR'), ('keyboard', 'Keyboard'), ('laptops', 'Laptops')], max_length=20, null=True),
        ),
    ]
